spring:
  application:
    name: id-generator
  datasource:
    url: jdbc:h2:mem:id_generator
    username: root
    password: root
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:quick/pager/id/generator/demo/mapper/*.xml
  type-aliases-package: quick.pager.id.generator.demo.model
server:
  port: 8081
  tomcat:
    max-threads: 1000
    max-connections: 10000