spring:
  application:
    name: id-generator
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/id_generator?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jdbc:
    template:
      query-timeout: 3

server:
  tomcat:
    max-threads: 1000
    max-connections: 10000

id:
  generator:
    redis: true